### ISSUE TITLE
Tooltip inside text position is not coming right.

### ISSUE THREAD

**Issue by sahilpandya** [FormidableLabs/victory-native#190]
Hi, 
I am using VictoryVoronoiContainer for render tooltip but in tooltip text is not coming on right position. I am attaching screen-shot.

My `"victory-native": "^0.16.1","react-native": "0.40.0" and "react-native-svg": "5.1.8"`.
<img width="255" alt="screen shot 2017-11-17 at 11 50 59 am" src="https://user-images.githubusercontent.com/13818308/32932233-a7a0721c-cb8d-11e7-8d63-7ac046ac05c0.png">

**Comment by blackkey520** [comment]
same problem

**Comment by sahilpandya** [comment]
Any Update ?

**Comment by blackkey520** [comment]
@sahilpandya  i have try update victory-native to latest version,but the new problem coming out,it seems like 'react-native-svg' can't support to com.android.support:appcompat-v7:26.1.0 follow the [https://github.com/react-native-community/react-native-svg/issues/511](link) to see detail

**Comment by sahilpandya** [comment]
Yes, But I am trying in IOS device, and also according to my react native version, am not able to update react-native-svg package version otherwise it won't work.

**Comment by boygirl** [comment]
Sorry for the confusion. This issue is caused by a version mismatch between `victory-native` and `react-native-svg`. I've added a note to the readme concerning version requirements.  https://github.com/FormidableLabs/victory-native/pull/192/files You will also want to be aware that `react-native-svg` has very strict version requirements for `react` and `react native`. Please refer to the `react-native-svg` docs concerning specific versions.
