### ISSUE TITLE
Native component RNSVGSvgView does not exist

### ISSUE THREAD

**Issue by danieldelouya** [FormidableLabs/victory-native#195]
Just upgraded to 
"react-native-svg": "6.0.0",
"victory-native": "^0.16.1"

Now when i try to show a chart (exact same previously working code from earlier versions of the above) gives me the error: Native component RNSVGSvgView does not exist 

It's on iOS btw.

**Comment by blackkey520** [comment]
same problem

**Comment by danieldelouya** [comment]
Hope we get an update asap from the team

**Comment by boygirl** [comment]
@danieldelouya @blackkey520 Thanks for this issue. I'll try to reproduce.

**Comment by goldenmaya** [comment]
Same problem =(

**Comment by DrRefactor** [comment]
Same here, any workarounds?

**Comment by danieldelouya** [comment]
Still waiting as well

**Comment by dorraba** [comment]
Same here +1

**Comment by danieldelouya** [comment]
@boygirl Any news regarding this? Can't update RN/React/VictoryNative until this has been resolved.

**Comment by danieldelouya** [comment]
Update: 
I upgraded to:
"victory-native": "^0.16.1" 
"react-native-svg": "^6.0.1-rc.1"
 "react-native": "^0.51.0"

And now it works. Found out a library i was using was using an older version of react-native-svg which caused the problem.

**Comment by boygirl** [comment]
Yes, I believe this issue was caused by version mis-match. I haven't been able to reproduce it.

**Comment by bdspen** [comment]
I have been stuck on this for some time and have reproduced the error, here are my dependencies:
`
...
{
  "dependencies": {
    "moment": "^2.19.3",
    "query-string": "^5.0.1",
    "react": "16.0.0",
    "react-intl": "^2.4.0",
    "react-native": "^0.51.0",
    "react-native-elements": "^0.18.2",
    "react-native-svg": "^6.0.1-rc.1",
    "react-native-vector-icons": "^4.4.2",
    "react-navigation": "^1.0.0-beta.21",
    "victory-native": "^0.16.1"
  }
...
}
`
I have also tried removing the node_modules forlder and reinstalling, and linking with react-native link.

The other thing I tried was the versions on the [react-native-svg](https://github.com/react-native-community/react-native-svg#notice).

**Comment by xanderberkein** [comment]
I had the same error. This issue seems to happen when you have a Podfile in your react-native project. In this case, the automatic linking of *react-native-svg* with `react-native link react-native-svg` fails. You need to manually link *react-native-svg* by following the first two steps in the docs (https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking)

**Comment by ruinangel** [comment]
I'm on IOS.

First, I got `ld: library not found for -lRNSVG-tvOS` when I built with `react-native run-ios`
Then,I delete `libRNSVG.a` in `Build Phases` with XCode

Retry, It works.

**Comment by dewwwald** [comment]
@ruinangel @xanderberkein your information was what I needed. To consolidate the solution that worked for me: 

(A note this happened after I updated NodeJs, so that might have something to do with it, however I introduced SVG's first thing after updating so I can't be sure).

Fix post update issues:
1. remove node modules
2. install node modules

Fix the error as described above:
1. Follow steps 1 and 2 as @xanderberkein mentioned described here https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking.
2. Make sure not to include the apple tv (there seem to be a big there).
3. if you used react native link there will be references to the libRNSVG.a package. You can remove those.

Another note this is how I solved this issue, I am by no means an expert with Native code and would like to point out that an issue has to be made most likely on the RNSVG package. I am happy to do that but require some guidance in getting more information.
