### ISSUE TITLE
Problem with label in VictoryPie

### ISSUE THREAD

**Issue by ngocht143** [FormidableLabs/victory-native#268]
### The Problem

Hi everyone, 
I'm working with VictoryPie, everything is perfect except the issue with label is overflowed for each item in the pie chart. This is the example when data is too small: [http://prntscr.com/im5qsh](http://prntscr.com/im5qsh)
`<VictoryPie
data={[
    { x: "Cats", y: 3 },
    { x: "Dogs", y: 99 },
    { x: "Birds", y: 1 }
  ]}
/>`

Version:
"react-native": "0.51.0",
"react-native-svg": "^6.2.2",
"victory-native": "^0.16.6"

**Comment by boygirl** [comment]
@ngocht143 Victory doesn't have any sort of constraint system for detecting when elements overlap. If you have a pie chart with very small slices you might consider using a legend rather than labels, or using tooltips rather than static labels. You could also write a custom label component with a bit of logic for changing the position of labels based on the data coming in. You can read about custom components here: https://formidable.com/open-source/victory/guides/custom-components/
