### ISSUE TITLE
render VictoryChart will crash when more times ----only on android

### ISSUE THREAD

**Issue by samuelltk** [FormidableLabs/victory-native#27]
getTransitionData() {
    const n = random(4, 10)
    return range(n).map((i) => {
      return {
        x: i,
        y: random(2, 10)
      };
    });
  }

  componentDidMount() {
    setInterval(() => {
      this.setState({
        transitionData: this.getTransitionData(),
      });
    }, 1000);
  }

  render() {
    var datas=this.state.transitionData;
    return (
      <View style={styles.container}>
        <VictoryChart
          width={width}
          padding={{left:50,right:25,top:20,bottom}}
          >
            <VictoryAxis
              style={{
                axis: {stroke: "black", strokeWidth:1},
                ticks: {stroke: "red",size:4},
                tickLabels: {fontSize: 18},
                axisLabel: {fontsize: 36}
              }}
              tickValues={[0,1,2,3,4,5,6,7,8]}
              domain={[0, 9]}
              orientation="bottom"
              tickFormat={(x) => x}/>
            <VictoryAxis
              dependentAxis
              style={{
                axis: {stroke: "black", strokeWidth:1},
                ticks: {stroke: "red",size:4},
                grid: {stroke: "gray",strokeWidth: 1,strokeDasharray:"5,5"},
                tickLabels: {fontSize: 12},
              }}
              domain={[-7, 20]}
              tickFormat={(y) => y}
            />
            <VictoryLine
              label="Line"
              style={{
                data: {
                  stroke: "teal",
                  strokeWidth:1,
                },
                labels: {fontSize: 12}
              }}
              data={datas}/>

            <VictoryScatter
              width={400}
              height={300}
              standalone={false}
              style={{
                data: {
                  fill: (data) => data.y < 2 ? "red" : "green"
                },
                labels: {
                  fill: "#ff00ff",
                  fontSize: 14,
                  padding: 12
                }
              }}
              size={4}
              labels={[
               "a", "", "", "MaxValue",
              ]}
              data={datas}
            />
        </VictoryChart>
      </View>
    );
  }
}

The app will crash when states change more times. please help me, thanks.

10-27 23:09:21.858 15712-15762/com.myvictorytest A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x90cd005c in tid 15762 (mqt_js)
10-27 23:09:24.828 15712-15712/com.myvictorytest I/Choreographer: Skipped 170 frames! The application may be doing too much work on its main thread.

**Comment by samuelltk** [comment]
Is there anything I can do to try to solve the problem? @boygirl @bmathews @waffle-iron @ebrillhart

**Comment by jevakallio** [comment]
@samuelltk we are also suffering from this problem at https://github.com/FormidableLabs/victory-uiexplorer-native/issues/1. The issue happens mainly in development builds, as the production build of the UIExplorer app seems stable in on-device testing.

We are working on this. It's an issue with `react-native-svg` library, tracked at https://github.com/react-native-community/react-native-svg/issues/38. The svg->bitmap rendering triggers this React Native issue https://github.com/facebook/react-native/issues/6760, which is in turn possibly caused by the Fresco image manager issue https://github.com/facebook/fresco/issues/1363#issuecomment-233865933.

The fix we are exploring is to replace the SVG bitmap rendering with Android `TextureView` rendering, as proposed in comment https://github.com/react-native-community/react-native-svg/issues/38#issuecomment-256556108.

**Comment by samuelltk** [comment]
@jevakallio Thank you very much.

**Comment by jevakallio** [comment]
@samuelltk good news and bad news. The proposed fix has now landed to `react-native-svg` in `4.3.2`, and it seems to ease the problem a little, but it doesn't fix is completely. Production builds feel stable, and dev builds still crash occasionally but less often than previously.

We'll continue to investigate the root cause.

**Comment by jevakallio** [comment]
@samuelltk the fix on `react-native-svg` did not fix the issue, and has been rolled back in `4.3.3`. 

However I've discovered that the issue does not occur when you turn off the JS Dev mode in: `Developer Menu (Shake / Cmd+M) > Dev Settings > JS Dev Mode`. This makes it a bit harder do debug javascript errors, but in my tests the Victory charts are 100% stable with the dev mode off.

**Comment by samuelltk** [comment]
@jevakallio Thanks for your reply. I have tried to adjust it according to you steps,it's kind of useful, only crashed occasionally. what is the version of the following framework you've used?

"react-native-chart-android": "^1.0.5",
    "react-native-svg": "^4.3.3",
    "react-native-svg-mock": "^1.0.2",
    "victory-chart-native": "^1.2.0",
    "victory-core": "^9.2.4",
    "victory-core-native": "^3.0.0",
    "victory-pie-native": "^1.1.0"

**Comment by jevakallio** [comment]
@samuelltk I'm currently on the following versions:
```
    "react": "~15.3.2",
    "react-native": "~0.37.0",
    "react-native-mock": "^0.2.5",
    "react-native-svg": "^4.3.3",
    "react-native-svg-mock": "^1.0.2",
    "victory-chart": "13.2.4",
    "victory-core": "9.2.4",
    "victory-core-native": "^3.0.0"
```

My `victory-chart-native` is a local copy that I'm currently developing, but it's based on `1.2.0`.

Are you still experiencing crashes with the JS Dev Mode turned off?

**Comment by samuelltk** [comment]
Yes, I certainly turned off the JS Dev Mode. It only crashed once today.

**Comment by samuelltk** [comment]
It looks like everything is all right now.  Thank you very much. @jevakallio
