### ISSUE TITLE
It looks like events are not working on victory-pie-native as they work on victory-pie

### ISSUE THREAD

**Issue by danfernand** [FormidableLabs/victory-native#28]
Good afternoon! Im running into an issue where events for the slice don't seem to be firing as expected. I also am running the demo and it appears that there is no changes on clicking on a pie chart as there is demos on the browser implementation. Are these things coming down the road or am I doing something stupid!

Thanks again. Daniel

```
<VictoryPie
      colorScale={ colorScale }
      data={ data }
      events={ [{
        target: 'data',
        eventHandlers: {
          onTouch: (evt, context, index) => {
            onSliceClick(Number(index))
          },
        },
      }] }
      height={ height }
      innerRadius={ calcInnerRadius }
      labelRadius={ 130 }
      labels={ [] }
      padding={ 50 }
      standalone={ standalone }
      width={ width }
      x={ x }
      y={ y }
    />
```

**Comment by esutton** [comment]
Possible related issue added to bottom of issue #37

**Comment by GeeWee** [comment]
I cannot get ths to work either.

**Comment by marlti7** [comment]
i have the same problem, Have you solved it? @esutton

**Comment by Tzinov15** [comment]
I also have this issue

**Comment by ShaikhKabeer** [comment]
I am also facing the same one.

**Comment by karaoak** [comment]
Yes, events are not fired on iOS and Android.

**Comment by luizParreira** [comment]
On mobile the name of the event is `onPressIn`

**Comment by rajatgng** [comment]
it don't work either

**Comment by cchoe1** [comment]
I got this to work on an Android emulator by wrapping my VictoryPie component with an <Svg> component, as described here:

https://stackoverflow.com/questions/57227291/victory-native-events-props-not-working-in-react-native-event-not-firing-in

I used the first answer that mentioned using const ChartClick.  One thing it doesn't mention is that you need to obviously import these into your component file with the following:

`import { TouchableOpacity } from "react-native";`
`import Svg from "react-native-svg";`

Because I'm going for cross platform compatibility, this will allow the wrapper to be either TouchableOpacity or Svg for iOS and Android, respectively.  Once I wrap my <VictoryPie> component with <ChartClick> it recognizes "onPressIn" events.
