### ISSUE TITLE
LinearGradient on VictoryLine

### ISSUE THREAD

**Issue by cotorusso94** [FormidableLabs/victory-native#285]
Hello,
i'm trying to add gradient on VictoryLine without success.

I'm using react-native-svg LinearGradient.

The gradient apply as fill but not as stroke.

Any idea?

`
        <Svg>
          <Defs>
            <LinearGradient id="linear" x1="0%" y1="0%" x2="0%" y2="100%">
              <Stop offset="0%"   stopColor="green"/>
              <Stop offset="100%" stopColor="red"/>
            </LinearGradient>
          </Defs>
        </Svg>
        <VictoryLine
          animate={{
            onLoad: { duration: 3000 }
          }}
          height={200}
          width={500}
          style={{
            data: {
              stroke: 'url(#linear)',
              strokeWidth: 3
            }
          }}
          interpolation="natural"
          data={sampleData}
        />
`

**Comment by chiformihai** [comment]
I got it working by replacing <Svg> with <G>

**Comment by alexsmartens** [comment]
Hi,
for some reason I cannot get LineGradient working in my App. I am getting just black color instead of the gradient, like this:

![screenshot_20181106-104605](https://user-images.githubusercontent.com/26261714/48075626-af38db00-e1b1-11e8-975c-610e49c4cc77.png)

Here is my code:
```
<Svg style={{ height: 0, width: 0 }}>
    <Defs>
      <LinearGradient id="myGradient">
        <Stop offset="0%" stopColor="red"/>
        <Stop offset="25%" stopColor="orange"/>
        <Stop offset="50%" stopColor="gold"/>
        <Stop offset="75%" stopColor="yellow"/>
        <Stop offset="100%" stopColor="green"/>
      </LinearGradient>
    </Defs>
  </Svg>
  <VictoryChart>
    <VictoryArea
      style={{
        data: {fill: "url(#myGradient)"}
      }}
      data={[
        { x: 1, y: 2 },
        { x: 2, y: 3 },
        { x: 3, y: 7 },
        { x: 4, y: 4 },
        { x: 5, y: 5 }
      ]}
    />
  </VictoryChart>
```

What do you think?

**Comment by bear-junior** [comment]
@alexsmartens how could it work if you put width and height = 0 to SVG element?

<Svg style={{ height: 0, width: 0 }}>

Your gradient has now height and width = 0px, so you can't see any colors. Remove SVG element and replace with <G> element or put width and height.

**Comment by bear-junior** [comment]
@alexsmartens how could it work if you put width and height = 0 to SVG element?

`<Svg style={{ height: 0, width: 0 }}>`

Your gradient has now height and width = 0px, so you can't see any colors. Remove SVG element and replace with `<G>` element or put width and height (btw in RN `<Svg width={width} height={height}>`). You should also check LinearGradient element in docs for react-native-svg, because good implementation looks like this (just example):

```
<Svg
    height="150"
    width="300"
>
    <Defs>
        <LinearGradient id="grad" x1="0" y1="0" x2="170" y2="0">
            <Stop offset="0" stopColor="rgb(255,255,0)" stopOpacity="0" />
            <Stop offset="1" stopColor="red" stopOpacity="1" />
        </LinearGradient>
    </Defs>
    <Ellipse cx="150" cy="75" rx="85" ry="55" fill="url(#grad)" />
</Svg>
```
