### ISSUE TITLE
Is there a way o render million the values without problems?

### ISSUE THREAD

**Issue by ericklarac** [FormidableLabs/victory-native#305]
![image](https://user-images.githubusercontent.com/8422946/39451443-4f49ee30-4c94-11e8-9daf-1a4388e64c4e.png)

I would like to render k values and million values and display the correspondent value on the axis, no matter if it just show 1M or 2.34K.

Will appreciate any help.

**Comment by boygirl** [comment]
@ericklarac yes. The values on your axis will automatically be generated to match your data. You will probably want to adjust the padding on your chart to accommodate longer numbers, or use the `tickFormat` prop on `VictoryAxis` to display your values as something like `1M` rather than `1,000,000`. The `tickFormat` prop can accept a function of the tickValue, so you should be able to format it correctly regardless of whether you're dealing with millions or thousands
