### ISSUE TITLE
How to get x,y coordinate upon tapping anywhere within the chart?

### ISSUE THREAD

**Issue by xkawi** [FormidableLabs/victory-native#342]
# Feature Requests

### Checklist

* [x] My feature request is specific to `victory-native`. (Feature requests that do not _specifically_ address native functionality should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

My use case is basically to add a new line graph upon tapping on one point, drag, and lift my finger on another point anywhere within the chart area (in this case line chart). This is what I have tried so far:

```
lineGraphStartTouched = touchStartEvt => console.log('touchStart', touchStartEvt.nativeEvent)

lineGraphEndTouched = touchEndEvt => console.log('touchEnd', touchEndEvt.nativeEvent)

<VictoryChart
    width={420}
    theme={VictoryTheme.material}
    containerComponent={
        <VictoryCursorContainer
            onTouchStart={this.lineGraphStartTouched}
            onTouchEnd={this.lineGraphEndTouched}
        />
    }
>
    <VictoryLine
        style={{
            data: { stroke: '#c43a31' },
            parent: { border: '1px solid #ccc' },
        }}
        data={[
            { x: 1, y: 2 },
            { x: 2, y: 3 },
            { x: 3, y: 5 },
            { x: 4, y: 4 },
            { x: 5, y: 7 },
        ]}
    />
</VictoryChart>
```

The `onTouchStart` and `onTouchEnd` provides the starting and ending of `locationX` and `locationY`; however the locationX (e.g. 200.5) and locationY (e.g. 141.5) value is *not* the X and Y value of graph data (e.g. 1.5, 2.5). My question is that, am I on the right direction with regards to the use case what I am implementing? if yes, how could I "map" the locationX and locationY to the X,Y value of the graph data? If not, any input on how could I implement the feature that I want?

**Comment by boygirl** [comment]
@xkawi you can use the `Selection` helper from `victory-core` like 

`Selection.getSVGEventCoordinates(evt)` <- this will give you the _svg_ rather than _screen_ coordinates.

Then you can use the scale from your chart to translate your svg coordinates into data coordinates.
`x: scale.x.invert(x), y: scale.y.invert(y)` 

The `scale` prop will be provided to `VictoryCursorContainer`.

That's the general solution.  The much easier thing to do would be to use the `onCursorChange` callback on `VictoryCursorContainer`. It will be called with your new cursor value and the rest of the props on `VictoryCursorContainer`.  You can read about it here:https://formidable.com/open-source/victory/docs/victory-cursor-container/#oncursorchange
