### ISSUE TITLE
[Android] Animated line without data prop fails

### ISSUE THREAD

**Issue by jevakallio** [FormidableLabs/victory-native#35]
The following, minimal animation example in victory-chart-native demo app fails with error `Error while updating property 'd' in shadow node of type: RNSVGPath`:

```
        <VictoryLine
          style={{data: this.state.style}}
          interpolation="basis"
          animate={{duration: 1500}}
          y={this.state.y}
        />
```

The same  line animation works correctly, when the `data` prop is specified:

```
        <VictoryLine
          style={{data: this.state.style}}
          interpolation="basis"
          animate={{duration: 1500}}
          data={range(100).map((x) => x / 100).map((x) => ({
            x, y: this.state.y({x})
          }))}
        />
```

![screen shot 2016-11-28 at 16 00 10](https://cloud.githubusercontent.com/assets/1203949/20675360/e9bf4752-b583-11e6-80b0-85db46d5ec63.png)

**Comment by levsero** [comment]
https://github.com/FormidableLabs/victory-native/issues/129 is the same issue, it appears to happens if the data is empty (or only has a single point).

**Comment by joncursi** [comment]
I have the same issue on Android. The odd thing is that it goes away if you enable "Debug JS Remotely" in the dev menu. But that's obviously not a viable fix because production builds do not have debugging.

Similar issue with this Debug Menu weirdness cropped up here too: https://github.com/FormidableLabs/victory-native/issues/128

Anyone have ideas on how to solve?

**Comment by abolger** [comment]
I am also having this issue and need a fix.  Kudos for figuring out it goes away on debug, I was going crazy trying to figure out what I'd done to break it.

**Comment by fourcolors** [comment]
Yup, I have the same issue here too!
