### ISSUE TITLE
App Crashes when touching Graph?

### ISSUE THREAD

**Issue by 2joocy** [FormidableLabs/victory-native#403]
The issue that I am having, is when using React Navigation, and you switch tabs using the createBottomTabNavigator, and then switch back to click on the graph, it crashes on Android > 9.0.

I currently have the following code in my app

```
render() {

        const window = Dimensions.get('window');

        return(
            
            <VictoryChart
                height={Math.round((window.height / 100) * 45)}
                padding={{ top: 40, bottom: 45, left: 35, right: 15 }}
                containerComponent={
                    <VictoryBrushContainer
                        brushDomain={{y: [4, 10]}}
                        allowResize={false}
                        allowDrag={false}
                        brushStyle={{stroke: "transparent", fill: '#2FADBF', fillOpacity: 0.2}}
                    />
                }
            >

                <Defs>
                    <LinearGradient id="gradient1" x1="0%" y1="0%" x2="100%" y2="0%">
                        <Stop offset="0%" stopColor="#a200ff" />
                        <Stop offset="100%" stopColor="#01fffc" />
                    </LinearGradient>
                </Defs>

                <VictoryLabel
                    style={{ fill: "#7c80a3" }}
                    text="Bingo"
                    x={8}
                    y={10}
                />

                <VictoryAxis
                    domain={[0, 24]}
                    tickCount={12}
                    minDomain={{y: 1}}
                    style={{
                        axis: { stroke: "#394092" },
                        ticks: { fill: "#7c80a3" },
                        tickLabels: { fill: "#7c80a3" }
                    }}
                />

                <VictoryAxis
                    dependentAxis
                    domain={[0, 25]}
                    style={{
                        axis: { stroke: "none" },
                        grid: { stroke: "#394092" },
                        ticks: { fill: "#7c80a3" },
                        tickLabels: { fill: "#7c80a3" }
                    }}
                />
        
                <VictoryLine
                    containerComponent={
                        <VictoryContainer
                            height={15}
                            width={16}
                            style={{border: "1px solid #ccc"}}
                        />
                        }       
                    interpolation="natural"
                    style={{
                        data: { stroke: "#33E0FF", strokeWidth: 3 }
                    }}
                    data={[
                        { x: 1, y: 2 },
                        { x: 2, y: 3 },
                        { x: 3, y: 5 },
                        { x: 4, y: 4 },
                        { x: 5, y: 7 }
                    ]}
                />
            </VictoryChart>
        );
    }

```

Versions:

SVG: 6.5.0
Victory Native: 30.5

Even on Android 9.0 and above, when trying to do this it laggs out the whole application for some seconds, although doesn't crash.

**Comment by boygirl** [comment]
@2joocy is there an error associated with the crash? Does it still crash if you remove the `Defs` and `VictoryLabel` children?

**Comment by boygirl** [comment]
Interesting... I haven't seen this one before, but based on the error I would guess it's choking one some fallback within Victory. Something with a `return someElement || null`

I'm guessing the error goes away when you remove `VictoryBrushContainer`. It looks like you're not using any of the events on `VictoryBrushContainer` so you might try passing the `disableContainerEvents` prop to `VictoryBrushContainer`. This will turn off all `panResponder` events that are usually registered to your parent container, so the parent chart wont be interactive any more. That might help, but I'm not sure of the root cause of the problem so I can't say for sure

A few general pointers that might help to simplify your chart:
- try to keep all your domain related props on your top level Victory component (VictoryChart), since it will need to reconcile the domain for all its children anyway
- container components supplied to children will not have any effect

**Comment by 2joocy** [comment]
We're using the Container as like a visual of a "goal" that the graph has to be in. Are there any other container options to use?

**Comment by boygirl** [comment]
You could also achieve the save effect with a `VictoryArea` child (or even a plain `Rect` child with a bit of work)
