### ISSUE TITLE
Right Axis Orientation Draws Data Backwards

### ISSUE THREAD

**Issue by joncursi** [FormidableLabs/victory-native#41]
I noticed that when attempting to orient the y-axis on the right side, in addition to just the axis moving to the right, the data appears to invert itself.

How the chart looks without a custom orientation:

```
<VictoryAxis
        dependentAxis
/>
```

<img width="338" alt="screen shot 2016-12-29 at 3 10 35 pm" src="https://cloud.githubusercontent.com/assets/4974609/21553852/f93191f0-cdd8-11e6-9bdf-d3ddb4a051f2.png">

How the chart looks after orienting on the right:

```
<VictoryAxis
        dependentAxis
        orientation="right"
/>
```

<img width="345" alt="screen shot 2016-12-29 at 3 09 48 pm" src="https://cloud.githubusercontent.com/assets/4974609/21553863/077bb844-cdd9-11e6-97fc-fabc3478c82c.png">

The axis does move, but the data is now drawn backwards.

**Comment by boygirl** [comment]
@joncursi this is expected behavior for Victory. If you want to orient the axis differently without altering the data, you can change the `offsetX` and `offsetY` props on your axis components to move them around. You can read more about these props here http://formidable.com/open-source/victory/docs/victory-axis#offsetx-and-offsety. I'm closing this issue, but if you want to discuss more, I would ask you to open an issue on the main victory repo, as this issue is not specific to the native version of the library.
Thanks!
