### ISSUE TITLE
Single data point

### ISSUE THREAD

**Issue by JonasWho** [FormidableLabs/victory-native#42]
If I create a VictoryBar with only 1 data point, it gets right-aligned. I feel like it should be centered or be dynamic so I can choose to center it horizontally.
Yes, it might be a bit weird to make a chart with 1 data point, but the use-case is a chart that dynamically shows user data for day/week/month/year, and for year it is quite normal to have only one.

**Comment by boygirl** [comment]
@JonasWho This is the default behavior Victory uses when trying to calculate an automatic domain with insufficient data. You can change it by setting a domain on your chart manually when there is only one data point. I'm closing this issue, but if you feel like there is more to discuss, I would ask you to open an issue on the main victory repo instead, since this behavior is relevant to more than just the native version of Victory. 
Thanks!
