### ISSUE TITLE
not compatible with expo 32 - crashes on real IOS device

### ISSUE THREAD

**Issue by tuqire** [FormidableLabs/victory-native#436]
Hi,

I have had to update my version of Expo from `31` to `32` - as I needed a later version of the Facebook Ads SDK - and it appears to have broken Victory Native `31`. Whenever my app tries to render a `VictoryPolarAxis` component on IOS, the app crashes. This only appears to occur on a real IOS device and not on the simulator.

I thought this might have been because the version of `react-native-svg` was updated in Expo, but they only bumped from `8.0.8` to `8.0.10`, so seems unlikely.

If anyone could help me it would be appreciated.

Expo release notes: https://blog.expo.io/expo-sdk-v32-0-0-is-now-available-6b78f92a6c52

Versions:

```
"expo": "^32.0.5",
"react": "16.5.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
"victory-native": "^31.0.0"
```

**Comment by bkniffler** [comment]
I'm having the same error. I'm not sure, but somewhere in the issues here or in react-native-svg someone guessed its due to the current React-Native version, and that the next version (which is due very soon with react-hooks) will fix that issue. 

Going to look for the thread again, not sure if I can find it though.

In my case, it is VictoryLine that doesn't work, but VictoryScatter works well. So you could temporarily check for the platform and use some other way to show data until this is fixed.

**Comment by bkniffler** [comment]
Okay, I'm not sure if this is really going to be fixed with next version of react-native.

I found some other issues:
__Empty "d" attribute in Path makes iOS app crash__
https://github.com/react-native-community/react-native-svg/issues/901

__iOS application crash when use <TSpan> with spaces as text__
https://github.com/react-native-community/react-native-svg/issues/904

__Crash when using Pattern__
https://github.com/react-native-community/react-native-svg/issues/840


I guess someone should check if any of these issues affects victory charts. In my case, I'm not able to use any chart data presentation components like VictoryChart except for VictoryScatter. Axis, labels etc all work.

**Comment by bkniffler** [comment]
Okay, strange enough, I had used VictoryScatter for a few days now. I just tried VictoryLine again on iOS and it works on my device (iOS 12, latest version). Don't know what's been causing this. Got `react-native-svg@8.0.10`, `react-native@https://github.com/expo/react-native/archive/sdk-31-with-hooks-dangerzone.tar.gz` and `victory-native@30.6.0`

**Comment by tuqire** [comment]
@bkniffler thanks for that. Are you installing a `react-native-svg@8.0.10` dependency on top of the one Expo provides? Also what version of Expo are you on? Expo 31 seems to be working fine with all charts for me.

**Comment by bkniffler** [comment]
It is Expo 32, and I installed react-native-svg explicitly! Unfortunately I can't experiment with the different combinations, but I can tell you that this exact one works!

**Comment by jamidwyer** [comment]
I had a similar issue when I updated to Expo 32. I traced it into react-native-svg's Path element and I suspect it's that the path contains a null where a 0 should be, but a deadline approached, so we rolled back to Expo 31 and it's all working great again. 

Thank you for making this awesome library available!

**Comment by vjsingh** [comment]
My iOS app crashes when I try to render an SVG where the path is an empty string (path='')

**Comment by mic-css** [comment]
I had the same issue with `VictoryLine` after upgrading to **expo 32**, specifically when providing an array to the `labels` prop. For some reason, providing a function fixes the issue.

I'm not installing `react-native-svg` separately.

```
"expo": "^32.0.0",
"react": "16.5.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
"victory-native": "^31.0.0"
```

**Comment by workspacedg** [comment]
I solved this problem using  Yarn, 
Remove :rm -rf package-lock.json , rm -rf node_modules . 
Install dependencies : yarn install .
