### ISSUE TITLE
only include the chart packages you actually use?

### ISSUE THREAD

**Issue by darrencruse** [FormidableLabs/victory-native#438]
fairly new to victory this might be a dumb question but we were looking under node_modules seeing which were the largest npm packages and it was the first we'd noticed how victory is split into quite a lot of packages.

my question is whether (comparable to how people pull in just the lodash functions they use rather than the whole library) I could have installed just those charting packages that I actually use.

where to be specific, I had initially installed using the simple:
```
npm install victory-native --save
```
And atm my app shows a single VictoryLine/VictoryScatter chart, yet under node_modules I see e.g. victory-voronoi, victory-candlestick, etc.

(and snooping at the metro generated bundle I do see those included in the bundle even though I'm not referencing them).

Thanks,

Darren

**Comment by sulaysumaria** [comment]
Maybe add some chart specific dependencies as peer dependencies so that If I want to use only VictoryPie, I will install it as a peer dependency.

**Comment by sulaysumaria** [comment]
@boygirl  thoughts?

**Comment by boygirl** [comment]
@sulaysumaria sorry for the delay. I think adding all the victory components as peerDependencies rather than actual dependencies would be a very poor solution for `victory-native`. The packages are really tightly coupled, so they should be real dependencies.

**Comment by sulaysumaria** [comment]
Ohhh... Is there any other way to reduce the dependencies?? Because I am just using VictoryPie and VictoryTheme but my app size increased by 4 MB for just adding victory-native...

Can't we do something like having core components, that are used in almost all other components, as dependencies and others as peer??

@boygirl

**Comment by boygirl** [comment]
For a while `victory-native` existed as several smaller packages too, but we moved away from that model for reasons you can read about here: https://github.com/FormidableLabs/victory-native/issues/52

**Comment by boygirl** [comment]
This metro issue might also be of interest to you: https://github.com/facebook/metro/issues/227

**Comment by sulaysumaria** [comment]
I just tried by removing other victory elements and built the apk. Turns out, the size was affected by just few KBs. So its not `victory-native` that is taking up the space!!

@boygirl I am ok with having a single package as it does not affect much.

@darrencruse its alright to have all the components it does not affect much. But if you still want to remove unused dependencies, here's what I did:

**Note**: Its a pretty long process and the difference in size does not make it worth though.

1. Clone this repo (Lets say `A`).
2. Go to `lib/index.js` and remove all the exports. Keep only the exports that you need.
3. Remove all the files from `lib/components` and `lib/helpers`.
4. Download this repo as zip to another location (Lets say `B`).
5. Edit npm lint script to check only in lib folder (`"lint": "eslint lib/**/*.js"`)
6. Run `npm run lint` and copy files from B to A that are reported as missing.
7. Repeat step 6 until there is not more error remaining. (Took me almost 10 iterations.)
8. Run `npm-check` (Install it via `npm i npm-check -g`)
9. Remove unused dependencies.
10. Run `npm pack`.
11. Install the `tgz` generated to your app.
12. Done!
