### ISSUE TITLE
Chart click events doesnot fire in iOS any version. 

### ISSUE THREAD

**Issue by santoshdahal12** [FormidableLabs/victory-native#471]
After couple of hours I found that I should wrap VictoryChart with SVG to make OnPressIn work. So I made the change ,it worked in android. But doesnot work in IOS.

The version details: 
"react": "16.6.3",
 "react-native": "0.57.8",
"react-native-svg": "^9.4.0",
victory-native: "^32.0.2"

I tested in ios XR , ios 8 plus . it works fine in android . 

The way I am using events is : like this

 events={[{
                        target: 'data',
                        eventHandlers: {
                            onPressOut: () => ({
                                target: 'data',
                                mutation: (props) => {
                                  console.log(props);
                                    return null;
                                }
                            })
                        }
                    }]}

**Comment by santoshdahal12** [comment]
If I remove the top SVg wrapper it works in ios but not in android

**Comment by boygirl** [comment]
@santoshdahal12 this is very odd. Based on what you've said I suspect there might be an issue with panResponder. You can try disabling panResponder if you aren't using any of the evented containers (VictoryVoronoiContainer, VictoryZoomContainer etc.) You can do this by adding `containerComponent={<VictoryContainer disableContainerEvents />}` to your outermost Victory component (usually VictoryChart)

**Comment by XiufuJ** [comment]
Have the same issue here. I'm using the latest version of react-native-svg and victory-native. When I wrap VictoryPie, VictoryLabel together in order to center the label inside the pie in a <Svg> on ios the events of VictoryPie would not work. If I removed that <Svg> the events could work but in this case, the  VictoryLabel could not be shown. I tried to use containerComponent={<VictoryContainer disableContainerEvents />}, but it's not working. Is it because of ios makes things <Svg> untouchable?
It works perfectly on Android.

**Comment by XiufuJ** [comment]
Anyone could help?

**Comment by punksta** [comment]
@XiufuJ thanks a lot!

**Comment by santoshdahal12** [comment]
@XiufuJ Thanks it worked for you. I am closing this issue . Please see how @XiufuJ has resolved and reopen the issue if this does not work for you.
