### ISSUE TITLE
I want scattered Point touching the inner graph having gradient -help wanted

### ISSUE THREAD

**Issue by basitmir** [FormidableLabs/victory-native#662]
I am having the scattered points but the thing is its not touching the inner graph having gradient color.
What i want is scatterd points touching the edges of inner gradient points 
![image](https://user-images.githubusercontent.com/41080267/128057662-ad85fcbc-02fb-4622-b4fb-8a8a70cdf253.png)

Here is code for the same https://snack.expo.dev/@basitmir/victroy-graph

**Comment by boygirl** [comment]
@basitmir the issue here is that you're using a type of interpolation for your area plot that does not respect the exact positions of the points. What about trying `interpolation="cardinal"` instead of `interpolation="basis"`

**Comment by basitmir** [comment]
@boygirl I also tried that but setting interpolation to cardinal does not give me entire circle at the end. Please have a look again i have update my query

**Comment by boygirl** [comment]
@basitmir I see what you're trying to do. Unfortunately Victory only includes a few options for interpolation (all provided by [`d3-shape`](https://github.com/d3/d3-shape#curves). 

That said, you can also provide your own function rather than using one of the named interpolation options that Victory provides. Some of the d3 interpolation curves actually have more options than are exposed when you just use the interpolation name. For example, the cardinal curve option includes a `tension` param that influences how the curve interpolates between points. It is meant to take an value between 0 and 1:

tension = 1
<img width="332" alt="Screen Shot 2021-08-03 at 11 00 59 AM" src="https://user-images.githubusercontent.com/3719995/128063943-10f51f86-5f50-41fb-a923-5980b3a845dd.png">

tension = 0 (default)
<img width="334" alt="Screen Shot 2021-08-03 at 11 01 12 AM" src="https://user-images.githubusercontent.com/3719995/128063984-4262065b-8943-46f2-84ef-b44eda8402a9.png">

but you can give it a negative value to even further exaggerate the curve and complete the circle
tension = -1
<img width="334" alt="Screen Shot 2021-08-03 at 11 01 26 AM" src="https://user-images.githubusercontent.com/3719995/128064187-d266ef27-0b9a-4676-81d1-c0e27a71144d.png">


To access these base curve functions do something like this:

```
import * as d3Shape  from "d3-shape";

const interpolator = d3Shape.curveCardinalClosed.tension(-1);

...
<VictoryArea
  interpolation={interpolator}
  ...
/>
```
