### ISSUE TITLE
Demo does not work on Android

### ISSUE THREAD

**Issue by nikhilag** [FormidableLabs/victory-native#68]
As per the readme file, we should just run "react-native run-android" under the victory-native directory to get the app running for Android. This is incorrect as we get an error message saying that the Android project was not found.

**Comment by riftshock** [comment]
I am having the same issue.. any ideas anyone out there??

**Comment by chrisbolin** [comment]
@nikhilag @riftshock there currently isn't an android demo. it turns out it's a bit harder to make the current setup work on android than iOS. I'll post some details, and would love some help!

**Comment by chrisbolin** [comment]
If anyone is interested in helping get a demo working on Android, here's the current situation:

### Demo requirements

- the demo should work after a simple single `npm install`
- the demo should load _local_ victory-native code in `lib/` not `node_modules/victory-native`, so that it can also be used to by victory-native contributors to test new features and fixes
- it's OK to rely on the react-native CLI being install globally
- `react-native` can only be installed in one place in a hierarchy, and therefore cannot be installed in `demo/node_modules`. If it is installed in two places, the packager will fail with `Duplicate module name … @providesModule declaration with the same name across two different files`

### iOS demo

- the iOS demo works by running two scripts: `start` and `demo:ios`. It also uses a Babel alias for `victory-native`.
- `start` script: initiates the RN packager: `./node_modules/react-native/packager/packager.sh start --reset-cache --projectRoots pwd, pwd/demo`
- `demo:ios` script: starts the  `react-native run-ios --project-path demo/ios`
- `demo/.babelrc` - uses the `module-resolver` plugin to assign an alias: `"victory-native": "./lib"`.

### Android demo notes

- my current and unfinished attempt to get the android demo working: https://github.com/FormidableLabs/victory-native/tree/android-demo
- there is no `--project-path` option for `react-native run-android`. I used `react-native run-android --root pwd/demo/` instead (note that `pwd` is required).
- `run-android` expects to find `demo/node_modules/react-native/react.gradle`
- if copy `react.gradle` to the expected path above (or it you just install `react-native` in `demo/node_modules`, which, remember, you shouldn’t do), you’ll run into the following error:

```
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
Could not resolve all dependencies for configuration ':app:_debugApk'.
 Configuration with name 'default' not found.
```

### Next steps

- is there a way to make the Android demo function under these requirements?
- if there isn't, should we pursue a separate user and contributor/developer demos? We might still face the struggles with a contributor/developer demo running on Android though. (The only advantage we'd have is that we could inconvenience contributors more than users, so the demo setup could be more convoluted)

**Comment by chrisbolin** [comment]
closed by https://github.com/FormidableLabs/victory-native/pull/93 - check out https://github.com/FormidableLabs/victory-native-demo
