### ISSUE TITLE
[Android] Animations disabled

### ISSUE THREAD

**Issue by jlo1** [FormidableLabs/victory-native#69]
Why disable animations for android? Noticed that all components override `shouldAnimate` to be false if os is "android":
```
  shouldAnimate() {
    return (Platform.OS === "android") ? false : Boolean(this.props.animate);
  }
```

Is there any plan to support animations for android soon?

**Comment by jevakallio** [comment]
This was a hack we had to push in order to work around a crashing issue with react-native-svg/Fresco on Android. We have however now upgraded to react-native-svg and this may be fixed.

See original issue: https://github.com/FormidableLabs/victory-native/issues/27

I'll try to test if this issue still persists, and we can re-enable the animations on Android.

**Comment by micchyboy** [comment]
The animations are still not working on Android. Any updates on this?

**Comment by hasLandon** [comment]
@micchyboy @jlo1 They have been re-enabled if you update to the latest version.
