### ISSUE TITLE
Top part of line halved when near the top of the graph

### ISSUE THREAD

**Issue by robcalcroft** [FormidableLabs/victory-native#83]
When the graph line gets near the top of the graph and sits on the very top of the graph, half the line appears to be hidden making it tough to see the top of the line
![pasted image at 2017_04_20 06_29 pm](https://cloud.githubusercontent.com/assets/3504764/25244178/95ef22e8-25f7-11e7-8be1-3b9ea882f94d.png)

**Comment by chrisbolin** [comment]
@robcalcroft this likely due to clipping, and is unfortunately to be expected; are you using the VictoryZoomContainer? (the zoom container relies on clipping)

You could manually set the domain for the `y` portion of the graph to give yourself some padding. e.g. in the above case you could have the maximum be `max(data) + 0.5 = 8.5`.

**Comment by robcalcroft** [comment]
Ahh ok I'll give that a try 😊

**Comment by chrisbolin** [comment]
@robcalcroft I should add that `domainPadding` can be a really quick fix to your problem, especially since it looks like you are concerned with clipping at the top of the graph. just try `domainPadding={2}` and see if you like it

**Comment by chrisbolin** [comment]
closing this issue, but feel free to ask more questions!

**Comment by robcalcroft** [comment]
Fab thanks for your help 👌

**Comment by chrisbolin** [comment]
🤘🤘

**Comment by JulianKingman** [comment]
For some reason domain padding didn't entirely work like this: `domainPadding={{y: [0, 5]}}`, but worked fine like this: `domainPadding={{y: 5}}`
